spring:
  application:
    name: zuul-server
server:
  port: 5555
  servlet:
    context-path: /cloud
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

# http"//localhost:5555/cloud[/endpoint/]
zuul:
  routes:
    eureka-client-products: /eureka/**
    eureka-feign-client: /feign/**
  sensitiveHeaders: Cookie, Set-Cookie